CREATE TABLE `UserPermission` (
  `id` VARCHAR(191) NOT NULL,
  `userId` VARCHAR(191) NOT NULL,
  `permission` ENUM('VIEW_DOCUMENTS', 'UPLOAD_DOCUMENT', 'DOWNLOAD_DOCUMENT', 'DELETE_DOCUMENT', 'RESTORE_DOCUMENT', 'EMPTY_TRASH', 'SHARE_DOCUMENT', 'RENAME_DOCUMENT', 'VIEW_TRASH', 'VIEW_SUBSCRIPTION') NOT NULL,
  `enabled` BOOLEAN NOT NULL DEFAULT true,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

  UNIQUE INDEX `UserPermission_userId_permission_key` (`userId`, `permission`),
  INDEX `UserPermission_permission_enabled_idx` (`permission`, `enabled`),
  PRIMARY KEY (`id`),
  CONSTRAINT `UserPermission_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

INSERT INTO `UserPermission` (`id`, `userId`, `permission`, `enabled`, `createdAt`, `updatedAt`)
SELECT UUID(), `User`.`id`, `PermissionValues`.`permission`, true, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)
FROM `User`
CROSS JOIN (
  SELECT 'VIEW_DOCUMENTS' AS `permission`
  UNION ALL SELECT 'UPLOAD_DOCUMENT'
  UNION ALL SELECT 'DOWNLOAD_DOCUMENT'
  UNION ALL SELECT 'DELETE_DOCUMENT'
  UNION ALL SELECT 'RESTORE_DOCUMENT'
  UNION ALL SELECT 'EMPTY_TRASH'
  UNION ALL SELECT 'SHARE_DOCUMENT'
  UNION ALL SELECT 'RENAME_DOCUMENT'
  UNION ALL SELECT 'VIEW_TRASH'
  UNION ALL SELECT 'VIEW_SUBSCRIPTION'
) AS `PermissionValues`;