export const DEFAULT_FOLDERS = [
  {
    id: "f-1",
    name: "Work & Contracts",
    slug: "work",
    description: "Client service agreements, NDA documents, and signed partner proposals.",
    color: "blue",
    bgLight: "bg-blue-50",
    textColor: "text-blue-600",
    borderColor: "border-blue-200/70",
  },
  {
    id: "f-2",
    name: "Finance & Taxes",
    slug: "finance",
    description: "Annual audit spreadsheets, expense statements, invoices, and quarterly tax filings.",
    color: "emerald",
    bgLight: "bg-emerald-50",
    textColor: "text-emerald-600",
    borderColor: "border-emerald-200/70",
  },
  {
    id: "f-3",
    name: "Personal Vault",
    slug: "personal",
    description: "Medical records, IDs, passport copies, resumes, and personal certificates.",
    color: "purple",
    bgLight: "bg-purple-50",
    textColor: "text-purple-600",
    borderColor: "border-purple-200/70",
  },
  {
    id: "f-4",
    name: "Design Assets",
    slug: "design",
    description: "Logos, brand guidelines, UI mockups, iconography packs, and banners.",
    color: "amber",
    bgLight: "bg-amber-50",
    textColor: "text-amber-600",
    borderColor: "border-amber-200/70",
  },
];
